wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.18.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1728790434
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 23
      - 37
      4: 3.11.9
      5: 0.18.3
      8:
      - 5
      13: linux-x86_64
batch:
  desc: null
  value: 8
dropout:
  desc: null
  value: 0
epochs:
  desc: null
  value: 170
erasing:
  desc: null
  value: 0.5
imgsz:
  desc: null
  value: 640
lr0:
  desc: null
  value: 0.0009447286477723164
optimizer:
  desc: null
  value: Adam
scale:
  desc: null
  value: 0.2
seed:
  desc: null
  value: 1337
