_wandb:
    value:
        cli_version: 0.18.2
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 13
                - 16
                - 19
                - 23
                - 47
                - 55
                - 61
            "4": 3.12.3
            "5": 0.18.2
            "8":
                - 5
            "12": 0.18.2
            "13": linux-x86_64
agnostic_nms:
    value: false
amp:
    value: true
augment:
    value: false
auto_augment:
    value: randaugment
batch:
    value: 1
bgr:
    value: 0
box:
    value: 7.5
cache:
    value: ram
cfg:
    value: null
classes:
    value: null
close_mosaic:
    value: 70
cls:
    value: 0.5
conf:
    value: null
copy_paste:
    value: 0
cos_lr:
    value: false
crop_fraction:
    value: 1
data:
    value: ./racoon_dataset.yml
degrees:
    value: 0
deterministic:
    value: true
device:
    value:
        - 0
dfl:
    value: 1.5
dnn:
    value: false
dropout:
    value: 0
dynamic:
    value: false
embed:
    value: null
epochs:
    value: 100
erasing:
    value: 0.4
exist_ok:
    value: true
fliplr:
    value: 0.5
flipud:
    value: 0
format:
    value: torchscript
fraction:
    value: 1
freeze:
    value: null
half:
    value: false
hsv_h:
    value: 0.015
hsv_s:
    value: 0.7
hsv_v:
    value: 0.4
imgsz:
    value: 640
int8:
    value: false
iou:
    value: 0.7
keras:
    value: false
kobj:
    value: 1
label_smoothing:
    value: 0
line_width:
    value: null
lr0:
    value: 0.01
lrf:
    value: 0.01
mask_ratio:
    value: 4
max_det:
    value: 300
mixup:
    value: 0
mode:
    value: train
model:
    value: yolov8x-seg.pt
momentum:
    value: 0.937
mosaic:
    value: 1
multi_scale:
    value: false
name:
    value: rac_seg_02
nbs:
    value: 64
nms:
    value: false
opset:
    value: null
optimize:
    value: false
optimizer:
    value: auto
overlap_mask:
    value: true
patience:
    value: 50
perspective:
    value: 0
plots:
    value: true
pose:
    value: 12
pretrained:
    value: true
profile:
    value: false
project:
    value: racoon_segmentation
rect:
    value: false
resume:
    value: false
retina_masks:
    value: false
save:
    value: true
save_conf:
    value: false
save_crop:
    value: false
save_dir:
    value: racoon_segmentation/rac_seg_02
save_frames:
    value: false
save_hybrid:
    value: false
save_json:
    value: false
save_period:
    value: 10
save_txt:
    value: false
scale:
    value: 0.5
seed:
    value: 0
shear:
    value: 0
show:
    value: false
show_boxes:
    value: true
show_conf:
    value: true
show_labels:
    value: true
simplify:
    value: false
single_cls:
    value: false
source:
    value: null
split:
    value: val
stream_buffer:
    value: false
task:
    value: segment
time:
    value: null
tracker:
    value: botsort.yaml
train:
    value:
        agnostic_nms: false
        amp: true
        augment: false
        auto_augment: randaugment
        batch: 1
        bgr: 0
        box: 7.5
        cache: ram
        cfg: null
        classes: null
        close_mosaic: 70
        cls: 0.5
        conf: null
        copy_paste: 0
        cos_lr: false
        crop_fraction: 1
        data: ./racoon_dataset.yml
        degrees: 0
        deterministic: true
        device:
            - 0
        dfl: 1.5
        dnn: false
        dropout: 0
        dynamic: false
        embed: null
        epochs: 100
        erasing: 0.4
        exist_ok: true
        fliplr: 0.5
        flipud: 0
        format: torchscript
        fraction: 1
        freeze: null
        half: false
        hsv_h: 0.015
        hsv_s: 0.7
        hsv_v: 0.4
        imgsz: 640
        int8: false
        iou: 0.7
        keras: false
        kobj: 1
        label_smoothing: 0
        line_width: null
        lr0: 0.01
        lrf: 0.01
        mask_ratio: 4
        max_det: 300
        mixup: 0
        mode: train
        model: yolov8x-seg.pt
        momentum: 0.937
        mosaic: 1
        multi_scale: false
        name: rac_seg_02
        nbs: 64
        nms: false
        opset: null
        optimize: false
        optimizer: auto
        overlap_mask: true
        patience: 50
        perspective: 0
        plots: true
        pose: 12
        pretrained: true
        profile: false
        project: racoon_segmentation
        rect: false
        resume: false
        retina_masks: false
        save: true
        save_conf: false
        save_crop: false
        save_dir: racoon_segmentation/rac_seg_02
        save_frames: false
        save_hybrid: false
        save_json: false
        save_period: 10
        save_txt: false
        scale: 0.5
        seed: 0
        shear: 0
        show: false
        show_boxes: true
        show_conf: true
        show_labels: true
        simplify: false
        single_cls: false
        source: null
        split: val
        stream_buffer: false
        task: segment
        time: null
        tracker: botsort.yaml
        translate: 0.1
        val: true
        verbose: true
        vid_stride: 1
        visualize: false
        warmup_bias_lr: 0
        warmup_epochs: 3
        warmup_momentum: 0.8
        weight_decay: 0.0005
        workers: 16
        workspace: 4
translate:
    value: 0.1
val:
    value: true
verbose:
    value: true
vid_stride:
    value: 1
visualize:
    value: false
warmup_bias_lr:
    value: 0.1
warmup_epochs:
    value: 3
warmup_momentum:
    value: 0.8
weight_decay:
    value: 0.0005
workers:
    value: 16
workspace:
    value: 4
