wandb_version: 1

batch:
  value: 8
dropout:
  value: 0
epochs:
  value: 216
erasing:
  value: 0.5
imgsz:
  value: 640
lr0:
  value: 0.036114069378199325
optimizer:
  value: SGD
scale:
  value: 0.5
seed:
  value: 42
