wandb_version: 1

batch:
  value: 8
dropout:
  value: 0
epochs:
  value: 170
erasing:
  value: 0.5
imgsz:
  value: 640
lr0:
  value: 0.0009447286477723164
optimizer:
  value: Adam
scale:
  value: 0.2
seed:
  value: 1337
