version: '3.8'
services:
  video_processor:
    build: .
    volumes:
      - ./service_account.json:/app/service_account.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service_account.json
      - INPUT_SOURCE=${INPUT_SOURCE}
      - OUTPUT_PATH=${OUTPUT_PATH}
      - FRAME_RATE=${FRAME_RATE:-1}
    command: ["python", "rd_video_image_extractor.py"]
